version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: template
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
    ports:
      - 3310:33060
    networks:
      extnetwork:
        ipv4_address: 192.168.5.2
  template:
    depends_on:
      - mysql
    build: .
    ports:
      - 8080
    environment:
      - spring.profiles.active=dev
    networks:
      extnetwork:
        ipv4_address: 192.168.5.3
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - "/root/html:/usr/share/nginx/html"
      - "./nginx/conf/nginx.conf:/etc/nginx/conf.d/mysite.template"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      extnetwork:
        ipv4_address: 192.168.5.5
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1
