spring:
  application:
    name: template
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    context-path: /api

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.easymiracle.com.easymiracle.biz.repository.entity